# Generated by Django 3.1.3 on 2021-03-18 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gate_No', models.IntegerField()),
                ('Thermometer_Id', models.IntegerField()),
                ('Thermometer_Status', models.BooleanField()),
                ('Thermometer_Last_Active', models.DateTimeField(default=django.utils.timezone.now)),
                ('Oximeter_Id', models.IntegerField()),
                ('Oximeter_Status', models.BooleanField()),
                ('Oximeter_Last_Active', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
